apiVersion: v1
kind: Service
metadata:
  name: gin-ping-service
  labels:
    app: gin-ping-service
spec:
  type: LoadBalancer # This will expose your service to the outside world, ensure your k8s environment supports this
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gin-ping-service
